package app.fieldwatch.domain

/** Display-only translations. Assigned-number names stay unchanged for matching and logs. */
object RadioLabels {
    fun label(raw: String): String {
        names[raw.lowercase()]?.let { return it }
        if (" / " in raw) return raw.split(" / ").joinToString(" / ", transform = ::label)
        if (" + " in raw) return raw.split(" + ").joinToString(" + ", transform = ::label)
        if (raw.endsWith(" utilized")) return "使用率 ${raw.removeSuffix(" utilized") }"
        if (raw.startsWith("format ")) return "格式 ${raw.removePrefix("format ")}"
        if (raw.startsWith("Type ")) return "类型 ${raw.removePrefix("Type ")}"
        val hex = raw.indexOf(" 0x")
        if (hex > 0) return label(raw.take(hex)) + raw.substring(hex)
        return raw
    }

    private val names = mapOf(
        "Unknown" to "未知", "Public" to "公共地址", "Random" to "随机地址", "Anonymous" to "匿名地址",
        "Miscellaneous" to "杂项", "Computer" to "计算机", "Phone" to "手机", "LAN" to "局域网",
        "Network AP" to "网络接入点", "Audio" to "音频", "Video" to "视频", "A/V" to "音视频",
        "Peripheral" to "外设", "Imaging" to "影像设备", "Wearable" to "可穿戴设备", "Toy" to "玩具",
        "Health" to "健康设备", "Uncategorized" to "未分类", "Major" to "主类别",
        "Desktop" to "台式电脑", "Server" to "服务器", "Laptop" to "笔记本电脑",
        "Handheld PC/PDA" to "掌上电脑 / PDA", "Palm-size PDA" to "掌上 PDA",
        "Wearable computer" to "可穿戴计算机", "Tablet" to "平板电脑", "Cellular" to "蜂窝电话",
        "Cordless" to "无绳电话", "Smartphone" to "智能手机", "Wired modem" to "有线调制解调器",
        "voice gateway" to "语音网关", "Common ISDN access" to "通用 ISDN 接入",
        "Fully available" to "完全可用", "No service available" to "无可用服务",
        "Wearable headset" to "可穿戴耳麦", "Hands-free" to "免提设备", "Microphone" to "麦克风",
        "Loudspeaker" to "扬声器", "Headphones" to "头戴耳机", "Portable audio" to "便携音响",
        "Car audio" to "车载音响", "Set-top box" to "机顶盒", "HiFi audio" to "高保真音响",
        "VCR" to "录像机", "Video camera" to "视频摄像头", "Camcorder" to "摄像机",
        "Video monitor" to "视频监视器", "Video display and loudspeaker" to "视频显示器和扬声器",
        "Video conferencing" to "视频会议设备", "Gaming" to "游戏设备", "Joystick" to "操纵杆",
        "Gamepad" to "游戏手柄", "Remote control" to "遥控器", "Sensing device" to "传感设备",
        "Digitizer tablet" to "数位板", "Card reader" to "读卡器", "Digital pen" to "数字笔",
        "Handheld scanner" to "手持扫描器", "Handheld gestural input" to "手持手势输入设备",
        "keyboard" to "键盘", "pointing" to "指点设备", "keyboard/pointing" to "键盘 / 指点设备",
        "Display" to "显示器", "Camera" to "摄像头", "Scanner" to "扫描器", "Printer" to "打印机",
        "Wristwatch" to "腕表", "Pager" to "寻呼机", "Jacket" to "智能夹克", "Helmet" to "头盔",
        "Glasses" to "眼镜", "Robot" to "机器人", "Vehicle" to "车辆", "Doll" to "玩偶",
        "action figure" to "人偶", "Controller" to "控制器", "Game" to "游戏玩具",
        "Blood pressure monitor" to "血压计", "Thermometer" to "温度计", "Weighing scale" to "体重秤",
        "Glucose meter" to "血糖仪", "Pulse oximeter" to "血氧仪", "Heart" to "心率",
        "pulse rate monitor" to "脉率监测器", "Health data display" to "健康数据显示器",
        "Step counter" to "计步器", "Body composition analyzer" to "身体成分分析仪",
        "Peak flow monitor" to "峰值流量计", "Medication monitor" to "用药监测器",
        "Knee prosthesis" to "膝关节假体", "Ankle prosthesis" to "踝关节假体",
        "Generic health manager" to "通用健康管理设备", "Personal mobility device" to "个人代步设备",
        "Limited Discoverable" to "有限可发现模式", "Positioning" to "定位", "Networking" to "联网",
        "Rendering" to "呈现", "Capturing" to "采集", "Object Transfer" to "对象传输",
        "Telephony" to "电话通信", "Information" to "信息服务",
        "Desktop Workstation" to "台式工作站", "Server-class Computer" to "服务器级计算机",
        "Handheld PC/PDA (clamshell)" to "翻盖式掌上电脑 / PDA", "Palm-size PC/PDA" to "掌上电脑 / PDA",
        "Wearable computer (watch size)" to "腕表大小的可穿戴计算机", "Docking Station" to "扩展坞",
        "All in One" to "一体机", "Blade Server" to "刀片服务器", "Convertible" to "翻转式电脑",
        "Detachable" to "可拆卸式电脑", "IoT Gateway" to "物联网网关", "Mini PC" to "迷你电脑",
        "Stick PC" to "电脑棒", "Watch" to "手表", "Sports Watch" to "运动手表",
        "Smartwatch" to "智能手表", "Clock" to "时钟", "Eye-glasses" to "眼镜", "Tag" to "标签",
        "Keyring" to "钥匙扣", "Media Player" to "媒体播放器", "Barcode Scanner" to "条码扫描器",
        "Ear Thermometer" to "耳温计", "Heart Rate Sensor" to "心率传感器", "Heart Rate Belt" to "心率带",
        "Blood Pressure" to "血压", "Arm Blood Pressure" to "臂式血压计", "Wrist Blood Pressure" to "腕式血压计",
        "Human Interface Device" to "人机接口设备", "Mouse" to "鼠标", "Touchpad" to "触控板",
        "Presentation Remote" to "演示遥控器", "Running Walking Sensor" to "跑步 / 步行传感器",
        "In-Shoe Running Walking Sensor" to "鞋内跑步 / 步行传感器",
        "On-Shoe Running Walking Sensor" to "鞋面跑步 / 步行传感器",
        "On-Hip Running Walking Sensor" to "腰部跑步 / 步行传感器", "Cycling" to "骑行设备",
        "Cycling Computer" to "自行车码表", "Speed Sensor" to "速度传感器", "Cadence Sensor" to "踏频传感器",
        "Power Sensor" to "功率传感器", "Speed and Cadence Sensor" to "速度与踏频传感器",
        "Control Device" to "控制设备", "Switch" to "开关", "Multi-switch" to "多路开关",
        "Button" to "按钮", "Slider" to "滑块", "Rotary Switch" to "旋转开关", "Touch Panel" to "触控面板",
        "Single Switch" to "单路开关", "Double Switch" to "双路开关", "Triple Switch" to "三路开关",
        "Battery Switch" to "电池供电开关", "Energy Harvesting Switch" to "能量采集开关",
        "Push Button" to "按键开关", "Dial" to "旋钮", "Network Device" to "网络设备",
        "Access Point" to "接入点", "Mesh Device" to "Mesh 设备", "Mesh Network Proxy" to "Mesh 网络代理",
        "Sensor" to "传感器", "Motion Sensor" to "运动传感器", "Air quality Sensor" to "空气质量传感器",
        "Temperature Sensor" to "温度传感器", "Humidity Sensor" to "湿度传感器", "Leak Sensor" to "漏水传感器",
        "Smoke Sensor" to "烟雾传感器", "Occupancy Sensor" to "占用传感器", "Contact Sensor" to "接触传感器",
        "Carbon Monoxide Sensor" to "一氧化碳传感器", "Carbon Dioxide Sensor" to "二氧化碳传感器",
        "Ambient Light Sensor" to "环境光传感器", "Energy Sensor" to "能耗传感器", "Color Light Sensor" to "彩色光传感器",
        "Rain Sensor" to "雨水传感器", "Fire Sensor" to "火灾传感器", "Wind Sensor" to "风力传感器",
        "Proximity Sensor" to "接近传感器", "Multi-Sensor" to "多功能传感器", "Multisensor" to "多功能传感器",
        "Flush Mounted Sensor" to "嵌入式传感器", "Ceiling Mounted Sensor" to "吸顶式传感器",
        "Wall Mounted Sensor" to "壁挂式传感器", "Energy Meter" to "能耗计", "Flame Detector" to "火焰探测器",
        "Vehicle Tire Pressure Sensor" to "车辆胎压传感器", "Light Fixtures" to "灯具", "Wall Light" to "壁灯",
        "Ceiling Light" to "吸顶灯", "Floor Light" to "落地灯", "Cabinet Light" to "柜灯", "Desk Light" to "台灯",
        "Troffer Light" to "嵌入式格栅灯", "Pendant Light" to "吊灯", "In-ground Light" to "地埋灯",
        "Flood Light" to "泛光灯", "Underwater Light" to "水下灯", "Bollard with Light" to "灯柱",
        "Pathway Light" to "步道灯", "Garden Light" to "庭院灯", "Pole-top Light" to "杆顶灯",
        "Spotlight" to "聚光灯", "Linear Light" to "线性灯", "Street Light" to "路灯", "Shelves Light" to "货架灯",
        "Bay Light" to "工矿灯", "Emergency Exit Light" to "应急出口灯", "Light Controller" to "灯光控制器",
        "Light Driver" to "灯光驱动器", "Bulb" to "灯泡", "Low-bay Light" to "低棚灯", "High-bay Light" to "高棚灯",
        "Fan" to "风扇", "Ceiling Fan" to "吊扇", "Axial Fan" to "轴流风扇", "Exhaust Fan" to "排气扇",
        "Pedestal Fan" to "落地扇", "Desk Fan" to "台扇", "Wall Fan" to "壁扇", "HVAC" to "暖通空调",
        "Thermostat" to "恒温器", "Humidifier" to "加湿器", "De-humidifier" to "除湿机", "Heater" to "加热器",
        "Radiator" to "暖气片", "Boiler" to "锅炉", "Heat Pump" to "热泵", "Infrared Heater" to "红外加热器",
        "Radiant Panel Heater" to "辐射板加热器", "Fan Heater" to "暖风机", "Air Curtain" to "风幕机",
        "Air Conditioning" to "空调", "Heating" to "供暖设备", "Access Control" to "门禁设备",
        "Access Door" to "门禁门", "Garage Door" to "车库门", "Emergency Exit Door" to "应急出口门",
        "Access Lock" to "门禁锁", "Elevator" to "电梯", "Window" to "窗户", "Entrance Gate" to "入口闸门",
        "Door Lock" to "门锁", "Locker" to "储物柜", "Motorized Device" to "电动设备",
        "Motorized Gate" to "电动门", "Awning" to "遮阳篷", "Blinds or Shades" to "百叶窗或遮阳帘",
        "Curtains" to "窗帘", "Screen" to "幕布", "Power Device" to "电源设备", "Power Outlet" to "电源插座",
        "Power Strip" to "插线板", "Plug" to "插头", "Power Supply" to "电源", "LED Driver" to "LED 驱动器",
        "Fluorescent Lamp Gear" to "荧光灯控制装置", "HID Lamp Gear" to "HID 灯控制装置",
        "Charge Case" to "充电盒", "Power Bank" to "移动电源", "Light Source" to "光源",
        "Incandescent Light Bulb" to "白炽灯泡", "LED Lamp" to "LED 灯", "HID Lamp" to "HID 灯",
        "Fluorescent Lamp" to "荧光灯", "LED Array" to "LED 阵列", "Multi-Color LED Array" to "多色 LED 阵列",
        "Low voltage halogen" to "低压卤素灯", "Organic light emitting diode (OLED)" to "有机发光二极管（OLED）",
        "Window Covering" to "窗饰", "Window Shades" to "遮阳帘", "Window Blinds" to "百叶窗",
        "Window Awning" to "窗用遮阳篷", "Window Curtain" to "窗帘", "Exterior Shutter" to "室外百叶窗",
        "Exterior Screen" to "室外遮挡屏", "Audio Sink" to "音频接收设备", "Standalone Speaker" to "独立音箱",
        "Soundbar" to "条形音箱", "Bookshelf Speaker" to "书架音箱", "Standmounted Speaker" to "支架音箱",
        "Speakerphone" to "免提电话", "Audio Source" to "音频源", "Alarm" to "报警器", "Bell" to "铃",
        "Horn" to "喇叭", "Broadcasting Device" to "广播设备", "Service Desk" to "服务台", "Kiosk" to "自助终端",
        "Broadcasting Room" to "广播室", "Auditorium" to "礼堂", "Motorized Vehicle" to "机动车",
        "Car" to "汽车", "Large Goods Vehicle" to "大型货车", "2-Wheeled Vehicle" to "两轮车",
        "Motorbike" to "摩托车", "Scooter" to "踏板车", "Moped" to "轻便摩托车", "3-Wheeled Vehicle" to "三轮车",
        "Light Vehicle" to "轻型车辆", "Quad Bike" to "四轮越野车", "Minibus" to "小型客车", "Bus" to "公交车",
        "Trolley" to "电车", "Agricultural Vehicle" to "农用车辆", "Camper" to "露营车", "Caravan" to "拖挂房车",
        "Recreational Vehicle" to "休旅车", "Motor Home" to "自行式房车", "Domestic Appliance" to "家用电器",
        "Refrigerator" to "冰箱", "Freezer" to "冷柜", "Oven" to "烤箱", "Microwave" to "微波炉",
        "Toaster" to "烤面包机", "Washing Machine" to "洗衣机", "Dryer" to "烘干机", "Coffee maker" to "咖啡机",
        "Clothes iron" to "电熨斗", "Curling iron" to "卷发棒", "Hair dryer" to "吹风机", "Vacuum cleaner" to "吸尘器",
        "Robotic vacuum cleaner" to "扫地机器人", "Rice cooker" to "电饭煲", "Clothes steamer" to "挂烫机",
        "Wearable Audio Device" to "可穿戴音频设备", "Earbud" to "入耳式耳机", "Headset" to "耳麦",
        "Neck Band" to "颈挂式耳机", "Left Earbud" to "左耳机", "Right Earbud" to "右耳机", "Aircraft" to "航空器",
        "Light Aircraft" to "轻型飞机", "Microlight" to "超轻型飞机", "Paraglider" to "滑翔伞",
        "Large Passenger Aircraft" to "大型客机", "AV Equipment" to "影音设备", "Amplifier" to "功放",
        "Receiver" to "接收机", "Radio" to "收音机", "Tuner" to "调谐器", "Turntable" to "唱机",
        "CD Player" to "CD 播放器", "DVD Player" to "DVD 播放器", "Bluray Player" to "蓝光播放器",
        "Optical Disc Player" to "光盘播放器", "Display Equipment" to "显示设备", "Television" to "电视机",
        "Monitor" to "监视器", "Projector" to "投影仪", "Hearing aid" to "助听器",
        "In-ear hearing aid" to "入耳式助听器", "Behind-ear hearing aid" to "耳背式助听器",
        "Cochlear Implant" to "人工耳蜗", "Home Video Game Console" to "家用游戏机",
        "Portable handheld console" to "便携游戏机", "Signage" to "信息标牌", "Digital Signage" to "数字标牌",
        "Electronic Label" to "电子标签", "Fingertip Pulse Oximeter" to "指夹式血氧仪",
        "Wrist Worn Pulse Oximeter" to "腕戴式血氧仪", "Weight Scale" to "体重秤",
        "Powered Wheelchair" to "电动轮椅", "Mobility Scooter" to "代步车",
        "Continuous Glucose Monitor" to "连续血糖监测仪", "Insulin Pump" to "胰岛素泵",
        "Insulin Pump, durable pump" to "耐用型胰岛素泵", "Insulin Pump, patch pump" to "贴片式胰岛素泵",
        "Insulin Pen" to "胰岛素笔", "Medication Delivery" to "给药设备", "Spirometer" to "肺量计",
        "Handheld Spirometer" to "手持肺量计", "Outdoor Sports Activity" to "户外运动设备",
        "Location Display" to "位置显示器", "Location and Navigation Display" to "位置与导航显示器",
        "Location Pod" to "定位模块", "Location and Navigation Pod" to "定位与导航模块",
        "Industrial Measurement Device" to "工业测量设备", "Torque Testing Device" to "扭矩测试仪",
        "Caliper" to "卡尺", "Dial Indicator" to "百分表", "Micrometer" to "千分尺", "Height Gauge" to "高度尺",
        "Force Gauge" to "测力计", "Industrial Tools" to "工业工具", "Machine Tool Holder" to "机床刀柄",
        "Generic Clamping Device" to "通用夹具", "Clamping Jaws/Jaw Chuck" to "夹爪 / 卡盘",
        "Clamping (Collet) Chuck" to "弹簧夹头", "Clamping Mandrel" to "夹紧芯轴", "Vise" to "虎钳",
        "Zero-Point Clamping System" to "零点定位夹紧系统", "Torque Wrench" to "扭矩扳手",
        "Torque Screwdriver" to "扭矩螺丝刀", "Cookware Device" to "炊具设备", "Pot and Jugs" to "锅具和壶",
        "Pressure Cooker" to "压力锅", "Slow Cooker" to "慢炖锅", "Steam Cooker" to "蒸锅",
        "Saucepan" to "奶锅", "Frying Pan" to "煎锅", "Casserole" to "砂锅", "Dutch Oven" to "铸铁炖锅",
        "Grill Pan/Raclette Grill/Griddle Pan" to "烤盘 / 芝士炉 / 煎烤盘", "Braising Pan" to "焖烧锅",
        "Wok Pan" to "炒锅", "Paella Pan" to "西班牙海鲜饭锅", "Crepe Pan" to "薄饼锅", "Tagine" to "塔吉锅",
        "Fondue" to "火锅", "Lid" to "锅盖", "Wired Probe" to "有线探针", "Wireless Probe" to "无线探针",
        "Baking Molds" to "烘焙模具", "Baking Tray" to "烤盘", "Immediate Alert" to "即时提醒",
        "Link Loss" to "连接丢失", "Tx Power" to "发射功率", "Current Time" to "当前时间",
        "Reference Time Update" to "参考时间更新", "Next DST Change" to "下次夏令时切换",
        "Glucose" to "血糖", "Health Thermometer" to "医用体温计", "Device Information" to "设备信息",
        "Heart Rate" to "心率", "Phone Alert Status" to "电话提醒状态", "Battery" to "电量",
        "Alert Notification" to "提醒通知", "Scan Parameters" to "扫描参数", "Running Speed and Cadence" to "跑速与步频",
        "Automation IO" to "自动化输入输出", "Cycling Speed and Cadence" to "骑行速度与踏频",
        "Cycling Power" to "骑行功率", "Location and Navigation" to "位置与导航", "Environmental Sensing" to "环境感知",
        "Body Composition" to "身体成分", "User Data" to "用户数据", "Bond Management" to "绑定管理",
        "Continuous Glucose Monitoring" to "连续血糖监测", "Internet Protocol Support" to "互联网协议支持",
        "Indoor Positioning" to "室内定位", "HTTP Proxy" to "HTTP 代理", "Transport Discovery" to "传输发现",
        "Fitness Machine" to "健身器械", "Mesh Provisioning" to "Mesh 配网", "Mesh Proxy" to "Mesh 代理",
        "Reconnection Configuration" to "重连配置", "Insulin Delivery" to "胰岛素输注",
        "Binary Sensor" to "二值传感器", "Emergency Configuration" to "紧急配置", "Authorization Control" to "授权控制",
        "Physical Activity Monitor" to "身体活动监测", "Elapsed Time" to "已用时间", "Generic Health Sensor" to "通用健康传感器",
        "Audio Input Control" to "音频输入控制", "Volume Control" to "音量控制", "Volume Offset Control" to "音量偏移控制",
        "Coordinated Set Identification" to "协同设备集标识", "Device Time" to "设备时间", "Media Control" to "媒体控制",
        "Generic Media Control" to "通用媒体控制", "Constant Tone Extension" to "恒定音调扩展",
        "Telephone Bearer" to "电话承载", "Generic Telephone Bearer" to "通用电话承载",
        "Microphone Control" to "麦克风控制", "Audio Stream Control" to "音频流控制", "Broadcast Audio Scan" to "广播音频扫描",
        "Published Audio Capabilities" to "已发布音频能力", "Basic Audio Announcement" to "基本音频通告",
        "Broadcast Audio Announcement" to "广播音频通告", "Common Audio" to "通用音频", "Hearing Access" to "助听接入",
        "Telephony and Media Audio" to "电话与媒体音频", "Public Broadcast Announcement" to "公共广播通告",
        "Electronic Shelf Label" to "电子货架标签", "Gaming Audio" to "游戏音频", "Mesh Proxy Solicitation" to "Mesh 代理请求",
        "Ranging" to "测距", "Cookware" to "炊具", "Voice Assistant" to "语音助手",
        "Generic Voice Assistant" to "通用语音助手", "Tire Pressure Monitoring System" to "胎压监测系统",
        "LE Limited Discoverable" to "BLE 有限可发现模式", "LE General Discoverable" to "BLE 通用可发现模式",
        "BR/EDR not supported" to "不支持 BR/EDR", "Simultaneous LE + BR/EDR (Controller)" to "同时支持 LE 和 BR/EDR（控制器）",
        "Simultaneous LE + BR/EDR (Host)" to "同时支持 LE 和 BR/EDR（主机）",
    ).mapKeys { it.key.lowercase() }
}
